name: new_payrightsystem
description: Payrightsystem Asensi.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  flutter_svg: ^0.12.1
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.3.0"
  barcode_scan: any
     #git: https://github.com/apptreesoftware/flutter_barcode_reader.git
  http: any
  google_fonts: ^1.1.1
  # device_info: ^1.0.0
  trust_fall: ^1.0.4
  url_launcher: ^5.4.11
  extended_navbar_scaffold: any
  flutter_vector_icons: ^0.2.0
  adv_fab: ^1.0.5
  fab_circular_menu: ^1.0.0

  

  
  #barcode_scan: ^1.0.0
  #qr_flutter: ^2.0.0
  #sweet_alert_dialogs: "^0.2.0"
  #trust_fall: ^1.0.4
  #haversine: ^1.0.2
  rive: ^0.0.1
  flutter_inappwebview: ^4.0.0+4
  webview_flutter: ^0.3.9+1
  imei_plugin: ^1.2.0
  flutter_shimmer: ^1.3.0
  badges: ^1.1.6
  #intl: ^0.15.8


  progress_dialog: ^1.2.1
  #charts_flutter: ^0.9.0
  pie_chart: ^4.0.1
  shimmer: ^1.1.2
  flutter_shimmer_widget: ^1.0.0



  flutter_automation: ^1.3.2  
  #connectivity: ^0.4.6+2
  provider: ^4.0.1
  intro_views_flutter: ^2.6.0
  rflutter_alert: ^1.0.3  
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  shared_preferences: ^0.5.6+1
  
  sqflite: any
  path_provider: '>=0.3.0'
  geolocator: ^5.3.0
  android_intent: ^0.3.4+8
  back_button_interceptor: ^4.2.3
  modal_progress_hud: ^0.1.3
  #access_settings_menu: ^0.0.1
  getflutter: ^1.0.10
  get: ^3.10.2
  #cupertino_icons: ^0.1.2

  flutter_staggered_animations: "^0.1.2"
  graphic: ^0.3.0
 
  screen_loader: ^2.0.1
  # overlay_support: latest_version
  another_flushbar: ^1.10.10
  flushbar: ^1.5.0
  flash: ^1.3.2
  overlay_support: ^1.0.5


  font_awesome_flutter: ^8.0.1
  firebase_core: ^0.5.0+1
  firebase_analytics: ^5.0.2
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^2.0.0+1
  fluttertoast: ^3.1.0
  gradient_app_bar: ^0.1.3
  flutter_slidable: "^0.5.3"
  fl_chart: ^0.2.0
  floating_action_bubble: 1.0.9
  ss_bottom_navbar: 0.1.0
  flutter_screenutil: ^0.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.7.0
  # flutter_icons:
  # ios: true
  # android: true
  # image_path_ios: "assets/img/logo.png"
  # image_path_android: "assets/img/logo.png"
  # adaptive_icon_background: "assets/img/logo.png"
  # adaptive_icon_foreground: "assets/img/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true

  assets:
   
      - assets/img/pocket.png
      - assets/pocket.png
      - assets/img/icon_success.png
      - assets/img/logo.png
      - assets/img/fingerprint.png
      - assets/img/settingbaru.png
      - assets/img/absorbed_in.png
      - assets/img/dashboard.png
      - assets/img/financial.png    
      - assets/img/data.png  
      - assets/img/privacy.png
      - assets/img/personal.png
      - assets/img/cancel.png
      - assets/img/cncl.png
      - assets/img/mobileApps.png
      - assets/img/unlock.png
      - assets/img/auth.png
      - assets/img/mobile.png
      - assets/img/personal_settings.png 
      - assets/img/new_notification.png 
      - assets/img/mobile_pay.png 
      - assets/img/error_location.png
      - assets/img/verified.png
      - assets/img/estimation-087BF3.png
      - assets/img/underconstruction.png
      - assets/img/going_home.png
      - assets/img/chart.png
      - assets/img/analitics.png
      - assets/img/data_statistic.png
      - assets/img/checked.png
      - assets/img/mini_absorbed_in.png
      - assets/img/mini_going_home.png
      - assets/img/bell-right.png
      - assets/img/app.png
      - assets/img/2.png
      - assets/img/auth.png
      - assets/img/report.png
      - assets/img/slider.png
      - assets/img/notification_1.png
      - assets/img/notification_2.png
      - assets/img/absenmasuk.png
      - assets/img/absenkeluar.png
      - assets/img/simpanlokasi.png
      - assets/img/bg_notification_header.png
      - assets/img/notifications.png

      - assets/animations/track.gif


      - assets/error.html
      - assets/webview_error.png


# The following section is specific to Flutter.


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: true

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
  # fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300          
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf          
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf          
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf          
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900        
